In [1]:
import pandas as pd
import csv

Let's view the first few columns of each dataframe to see what we are working with

In [24]:
gas_types = pd.read_csv('us_greenhouse_gas_emission_direct_emitter_gas_type.csv')
# RENAME ALL COLUMNS SO IT'S NOT SUCH AN EYESORE
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.ADDRESS1': 'Address Line 1'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.ADDRESS2': 'Address Line 2'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.CITY': 'City'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.CO2E_EMISSION': 'CO2 Emission'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.COUNTY': 'County'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.FACILITY_ID': 'Facility ID'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.GAS_CODE': 'Gas Code'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.GAS_NAME': 'Gas Name'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.LATITUDE': 'Latitude'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.LONGITUDE': 'Longitude'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.STATE': 'State'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.STATE_NAME': 'State Name'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.YEAR': 'Year'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.ZIP': 'Zip Code'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.FACILITY_NAME': 'Facility Name'})
gas_types = gas_types.rename(columns = {'V_GHG_EMITTER_GAS.COUNTY_FIPS': 'FIPS'})
# MAKE STRINGS UPPERCASE SO SEARCHING IS EASIER IN THE FUTURE
gas_types['City'] = gas_types['City'].str.upper()
gas_types['County'] = gas_types['County'].str.upper()
gas_types['Gas Code'] = gas_types['Gas Code'].str.upper()
gas_types['Gas Name'] = gas_types['Gas Name'].str.upper()
gas_types['Facility Name'] = gas_types['Facility Name'].str.upper()

# DROPPED COLUMNS WITH NO DATA
gas_types = gas_types.dropna(subset =['Address Line 1'] )

# DROPPED COLUMNS WITH MANY MISSING VALUES OR DATA THAT IS NOT IDENTIFYING
gas_types = gas_types.drop(columns = ['State', 'Address Line 2', 'FIPS'])

gas_types.head()

,Address Line 1,City,CO2 Emission,County,Facility ID,Gas Code,Gas Name,Latitude,Longitude,State Name,Year,Zip Code,Facility Name
0,1919 S. BROADWAY,GREEN BAY,58024.000,BROWN COUNTY,1000589,BIOCO2,BIOGENIC CO2,44.492500,-88.032300,WISCONSIN,2017,54304,GEORGIA-PACIFIC CONSUMER OPERATIONS LLC
1,850 12TH AVE,NEW YORK,134.500,NEW YORK,1000766,CH4,METHANE,40.771100,-73.991100,NEW YORK,2018,10019,59TH STREET
2,3379 HWY 482,NOBLE,6.854,SABINE,1009343,N2O,NITROUS OXIDE,31.621528,-93.724774,LOUISIANA,2012,71462,BAKER ROAD TREATER
3,1012 BEAUCHAMP ST,GREENVILLE,53562.000,WASHINGTON COUNTY,1003557,CH4,METHANE,33.392476,-91.017584,MISSISSIPPI,2017,38701,TEXAS GAS TRANSMISSION - GREENVILLE STATION
4,487 CORN CREEK ROAD,BEDFORD,7635064.700,TRIMBLE,1006542,CO2,CARBON DIOXIDE,38.584700,-85.411700,KENTUCKY,2018,40006,TRIMBLE COUNTY

The gas_type dataframe contains data about the location of emitter facilities and gas types emitted from each one. There are ~220,000 entries.

In [17]:
air_quality = pd.read_csv('us_air_quality_measures.csv')
air_quality.tail()

,MeasureId,MeasureName,MeasureType,StratificationLevel,StateFips,StateName,CountyFips,CountyName,ReportYear,Value,Unit,UnitName,DataOrigin,MonitorOnly
218630,296,Annual average ambient concentrations of PM 2....,Average,State x County,56,Wyoming,56045,Weston,2007,6.207126,µg/m³,Micograms per cubic meter,Monitor & Modeled,0
218631,296,Annual average ambient concentrations of PM 2....,Average,State x County,56,Wyoming,56045,Weston,2008,6.369764,µg/m³,Micograms per cubic meter,Monitor & Modeled,0
218632,296,Annual average ambient concentrations of PM 2....,Average,State x County,56,Wyoming,56045,Weston,2009,6.241708,µg/m³,Micograms per cubic meter,Monitor & Modeled,0
218633,296,Annual average ambient concentrations of PM 2....,Average,State x County,56,Wyoming,56045,Weston,2010,6.125957,µg/m³,Micograms per cubic meter,Monitor & Modeled,0
218634,296,Annual average ambient concentrations of PM 2....,Average,State x County,56,Wyoming,56045,Weston,2011,6.646464,µg/m³,Micograms per cubic meter,Monitor & Modeled,0

The air_quality dataframe contains air quality measures across different states/counties in the United States. It contains over 218,000 entries.

In [9]:
facilities = pd.read_csv('us_greenhouse_gas_emissions_direct_emitter_facilities.csv')
# RENAME ALL COLUMNS SO IT'S NOT SUCH AN EYESORE
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.ADDRESS1': 'Address Line 1'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.ADDRESS2': 'Address Line 2'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.CEMS_USED': 'CEMS Used'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.CITY': 'City'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.COUNTY': 'County'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.COUNTY_FIPS': 'FIPS'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.FACILITY_ID': 'Facilities ID'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.LATITUDE': 'Latitude'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.LONGITUDE': 'Longitude'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.PRIMARY_NAICS_CODE': 'NAICS Code'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.STATE': 'State'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.STATE_NAME': 'State Name'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.YEAR': 'Year'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.ZIP': 'Zip Code'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.FACILITY_NAME': 'Facility Name'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.SECONDARY_NAICS_CODE': 'Secondary NAICS Code'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.ADDITIONAL_NAICS_CODES': 'Additional NAICS Codes'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.COGENERATION_UNIT_EMISS_IND': 'Cogeneration Unit Emission Index(?)'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.EPA_VERIFIED': 'EPA Verified'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.PARENT_COMPANY': 'Parent Company'})
facilities = facilities.rename(columns = {'V_GHG_EMITTER_FACILITIES.PLANT_CODE_INDICATOR': 'Plant Code Indicator'})
# MAKE ADDRESSES ALL UPPERCASE, THEN DROP ROWS WITH NO ADDRESS
facilities['Address Line 1'] = facilities['Address Line 1'].str.upper()
facilities = facilities.dropna(subset =['Address Line 1'] )

facilities.head()

#add2_nan =facilities['Address Line 2'].isna().sum()
#add2_nan

/var/folders/m8/skfw9g2x4_g4pq5cv80_g24w0000gn/T/ipykernel_8802/972819466.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  facilities = pd.read_csv('us_greenhouse_gas_emissions_direct_emitter_facilities.csv')

,Address Line 1,Address Line 2,CEMS Used,City,County,FIPS,Facilities ID,Latitude,Longitude,NAICS Code,...,State Name,Year,Zip Code,Facility Name,Secondary NAICS Code,Additional NAICS Codes,Cogeneration Unit Emission Index(?),EPA Verified,Parent Company,Plant Code Indicator
0,301 COMMERCE DR. SUITE 3701,NaN,NaN,Fort Worth,NaN,NaN,1008536.0,35.533760,-97.529760,211111.0,...,TEXAS,2012.0,76102.0,TEP Barnett USA LLC 415 - Strawn Basin,NaN,NaN,N,NaN,CHESAPEAKE ENERGY CORP (100%),NaN
1,449 SHELL E&P COURT,NaN,NaN,Gibson,TERREBONNE,22109.0,1005071.0,29.628790,-90.917680,211112.0,...,LOUISIANA,2011.0,70358.0,North Terrebonne Gas Plant,NaN,NaN,N,NaN,ENTERPRISE GAS PROCESSING LLC (64.19%); DCP M...,NaN
2,5494 MALONE ROAD,NaN,NaN,MEMPHIS,SHELBY COUNTY,47157.0,1002466.0,34.999213,-89.906724,562212.0,...,TENNESSEE,2017.0,38116.0,SOUTH SHELBY LANDFILL,NaN,NaN,N,NaN,REPUBLIC SERVICES INC (100%),N
3,1601 WEEDON ISLAND DRIVE,NaN,NaN,SAINT PETERSBURG,Pinellas,12103.0,1001489.0,27.861300,-82.601200,221112.0,...,FLORIDA,2015.0,33702.0,P L Bartow Power Plant,NaN,NaN,N,NaN,DUKE ENERGY CORP (100%),Y
5,2237 HATCHER HILL RD,NaN,NaN,BACONTON,Mitchell,13205.0,1001409.0,31.386900,-84.081900,221112.0,...,GEORGIA,2011.0,31716.0,Baconton,NaN,NaN,N,NaN,SOWEGA ENERGY RESOURCES LLC. (65%); TEJAS POW...,NaN

The facilities dataframe contains data about each facility, namely address, location, and IDs (FIPS, NAICS). There are ~77,000 rows.